version: "3"
services:
    server:
        env_file: .env
        restart: always
        build: .
        extra_hosts:
           - "host.docker.internal:172.17.0.1"
        ports:
            - "${PORT}:${PORT}"